#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_interface.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_interface.yang


class ns(object):
    hash = 1069507739

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_interface"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_interface"

    prefix = "esc_interface"

