#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_disk.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_disk.yang


class ns(object):
    hash = 977395017

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_disk"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_disk"

    prefix = "esc_disk"

