#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_info.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_info.yang


class ns(object):
    hash = 157963728

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_info"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_info"

    prefix = "esc_info"

