#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_network.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_network.yang


class ns(object):
    hash = 746791368

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_network"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_network"

    prefix = "esc_network"

