#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_flavor.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_flavor.yang


class ns(object):
    hash = 1717526697

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_flavor"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_flavor"

    prefix = "esc_flavor"

