#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_opdata.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_opdata.yang


class ns(object):
    hash = 941279849

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_opdata"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_opdata"

    prefix = "esc_opdata"

    esc_opdata_none = 0
    esc_opdata_none_ = "none"
    esc_opdata_cold = 1
    esc_opdata_cold_ = "cold"
    esc_opdata_live = 2
    esc_opdata_live_ = "live"
