#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_property.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_property.yang


class ns(object):
    hash = 690595883

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc_property"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc_property"

    prefix = "esc_property"

