#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_datamodel.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_datamodel.yang


class ns(object):
    hash = 701389281

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_datamodel"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_datamodel"

    prefix = "esc_datamodel"

    esc_datamodel_telnet = 0
    esc_datamodel_telnet_ = "telnet"
    esc_datamodel_console = 1
    esc_datamodel_console_ = "console"
