#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_port_forwarding.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_port_forwarding.yang


class ns(object):
    hash = 1514235690

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_port_forwarding"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_port_forwarding"

    prefix = "esc_port_forwarding"

