#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_opdata_flavors.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_opdata_flavors.yang


class ns(object):
    hash = 315682996

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_opdata_flavors"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_opdata_flavors"

    prefix = "esc_opdata_flavors"

