#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_volume.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_volume.yang


class ns(object):
    hash = 1369448840

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_volume"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_volume"

    prefix = "esc_volume"

