#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_config_parameter.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_config_parameter.yang


class ns(object):
    hash = 1525898006

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_config_parameter"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_config_parameter"

    prefix = "esc_config_parameter"

