#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_rules.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_rules.yang


class ns(object):
    hash = 571441320

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_rules"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_rules"

    prefix = "esc_rules"

