#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_opdata_images.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_opdata_images.yang


class ns(object):
    hash = 1269768419

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_opdata_images"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_opdata_images"

    prefix = "esc_opdata_images"

