#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_config_data.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_config_data.yang


class ns(object):
    hash = 751191665

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_config_data"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_config_data"

    prefix = "esc_config_data"

