#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_file_locators.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_file_locators.yang


class ns(object):
    hash = 1884803687

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc_file_locators"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc_file_locators"

    prefix = "file_locators"

