#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_container_services.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_container_services.yang


class ns(object):
    hash = 1700787781

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_containers"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_containers"

    prefix = "esc_containers"

