#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_opdata_tenant.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_opdata_tenant.yang


class ns(object):
    hash = 837154265

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_opdata_tenant"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_opdata_tenant"

    prefix = "esc_opdata_tenant"

    esc_opdata_tenant_none = 0
    esc_opdata_tenant_none_ = "none"
    esc_opdata_tenant_cold = 1
    esc_opdata_tenant_cold_ = "cold"
    esc_opdata_tenant_live = 2
    esc_opdata_tenant_live_ = "live"
