#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_opdata_state_machines.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_opdata_state_machines.yang


class ns(object):
    hash = 661047337

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_opdata_state_machines"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_opdata_state_machines"

    prefix = "esc_opdata_state_machines"

