#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_policies.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_policies.yang


class ns(object):
    hash = 259963892

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_policies"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_policies"

    prefix = "esc_policies"

