#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_opdata_networks.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_opdata_networks.yang


class ns(object):
    hash = 1101608372

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_opdata_networks"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_opdata_networks"

    prefix = "esc_opdata_networks"

