#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_scaling.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_scaling.yang


class ns(object):
    hash = 1226208686

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_scaling"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_scaling"

    prefix = "esc_scaling"

