#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_vim_connector.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_vim_connector.yang


class ns(object):
    hash = 1379803910

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_vim_connector"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_vim_connector"

    prefix = "esc_vim_connector"

