#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_extension.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_extension.yang


class ns(object):
    hash = 2102219656

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc_extension"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc_extension"

    prefix = "esc_extension"

