#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_kpi.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_kpi.yang


class ns(object):
    hash = 1455509600

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_kpi"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_kpi"

    prefix = "esc_kpi"

