#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/esc_file_server.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module esc_file_server.yang


class ns(object):
    hash = 884311474

    id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_file_server"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_file_server"

    prefix = "esc_file_server"

