#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-esc-nc.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-esc-nc.yang


class ns(object):
    hash = 1092283822

    id = "http://tail-f.com/ns/ned-id/esc-nc"

    uri = "http://tail-f.com/ns/ned-id/esc-nc"

    prefix = "esc-nc"

    ned_id = 1379098150
    ned_id_ = "esc-nc:esc-nc"
    esc_nc_esc_nc = 1379098150
    esc_nc_esc_nc_ = "esc-nc"
