#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-esc-nc-1.0.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-esc-nc-1.0.yang


class ns(object):
    hash = 1343644036

    id = "http://tail-f.com/ns/ned-id/esc-nc-1.0"

    uri = "http://tail-f.com/ns/ned-id/esc-nc-1.0"

    prefix = "esc-nc-1.0"

    esc_nc_10x2e0_esc_nc_10x2e0 = 1189376274
    esc_nc_10x2e0_esc_nc_10x2e0_ = "esc-nc-1.0"
