#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/nso-licensing-proxy.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module nso-licensing-proxy.yang


class ns(object):
    hash = 1452370634

    id = "_esc-nc-1.0:esc-nc-1.0#http://cisco.com/yang/nso/licensing-proxy"

    uri = "_esc-nc-1.0:esc-nc-1.0#http://cisco.com/yang/nso/licensing-proxy"

    prefix = "licensing-proxy"

    licensing_proxy_unique_id = 1542040645
    licensing_proxy_unique_id_ = "unique-id"
    licensing_proxy_n = 1951310448
    licensing_proxy_n_ = "n"
    licensing_proxy_id = 1279252765
    licensing_proxy_id_ = "id"
    licensing_proxy_nso_licensing_proxy = 2113528637
    licensing_proxy_nso_licensing_proxy_ = "nso-licensing-proxy"
    licensing_proxy_entitlement = 1163688895
    licensing_proxy_entitlement_ = "entitlement"
