/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/esc_disk.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module esc_disk.yang */
public class esc_disk extends ConfNamespace {
    public static final int hash = 977395017;
    public int hash() {
        return esc_disk.hash;
    }

    public static final String id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_disk";
    public String id() {
        return esc_disk.id;
    }

    public static final String uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_disk";
    public String uri() {
        return esc_disk.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(esc_disk.uri);
    }

    public static final String prefix = "esc_disk";
    public String prefix() {
        return esc_disk.prefix;
    }

    public esc_disk() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
