/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/esc_network.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module esc_network.yang */
public class esc_network extends ConfNamespace {
    public static final int hash = 746791368;
    public int hash() {
        return esc_network.hash;
    }

    public static final String id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_network";
    public String id() {
        return esc_network.id;
    }

    public static final String uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_network";
    public String uri() {
        return esc_network.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(esc_network.uri);
    }

    public static final String prefix = "esc_network";
    public String prefix() {
        return esc_network.prefix;
    }

    public esc_network() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
