/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/esc_rules.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module esc_rules.yang */
public class esc_rules extends ConfNamespace {
    public static final int hash = 571441320;
    public int hash() {
        return esc_rules.hash;
    }

    public static final String id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_rules";
    public String id() {
        return esc_rules.id;
    }

    public static final String uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_rules";
    public String uri() {
        return esc_rules.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(esc_rules.uri);
    }

    public static final String prefix = "esc_rules";
    public String prefix() {
        return esc_rules.prefix;
    }

    public esc_rules() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
