/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/esc_kpi.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module esc_kpi.yang */
public class esc_kpi extends ConfNamespace {
    public static final int hash = 1455509600;
    public int hash() {
        return esc_kpi.hash;
    }

    public static final String id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_kpi";
    public String id() {
        return esc_kpi.id;
    }

    public static final String uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_kpi";
    public String uri() {
        return esc_kpi.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(esc_kpi.uri);
    }

    public static final String prefix = "esc_kpi";
    public String prefix() {
        return esc_kpi.prefix;
    }

    public esc_kpi() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
