/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/esc_volume.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module esc_volume.yang */
public class esc_volume extends ConfNamespace {
    public static final int hash = 1369448840;
    public int hash() {
        return esc_volume.hash;
    }

    public static final String id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_volume";
    public String id() {
        return esc_volume.id;
    }

    public static final String uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_volume";
    public String uri() {
        return esc_volume.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(esc_volume.uri);
    }

    public static final String prefix = "esc_volume";
    public String prefix() {
        return esc_volume.prefix;
    }

    public esc_volume() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
