/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/esc_info.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module esc_info.yang */
public class esc_info extends ConfNamespace {
    public static final int hash = 157963728;
    public int hash() {
        return esc_info.hash;
    }

    public static final String id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_info";
    public String id() {
        return esc_info.id;
    }

    public static final String uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_info";
    public String uri() {
        return esc_info.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(esc_info.uri);
    }

    public static final String prefix = "esc_info";
    public String prefix() {
        return esc_info.prefix;
    }

    public esc_info() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
