/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/esc_file_locators.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module esc_file_locators.yang */
public class esc_file_locators extends ConfNamespace {
    public static final int hash = 1884803687;
    public int hash() {
        return esc_file_locators.hash;
    }

    public static final String id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc_file_locators";
    public String id() {
        return esc_file_locators.id;
    }

    public static final String uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc_file_locators";
    public String uri() {
        return esc_file_locators.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(esc_file_locators.uri);
    }

    public static final String prefix = "file_locators";
    public String prefix() {
        return esc_file_locators.prefix;
    }

    public esc_file_locators() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
