/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/esc_config_data.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module esc_config_data.yang */
public class esc_config_data extends ConfNamespace {
    public static final int hash = 751191665;
    public int hash() {
        return esc_config_data.hash;
    }

    public static final String id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_config_data";
    public String id() {
        return esc_config_data.id;
    }

    public static final String uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_config_data";
    public String uri() {
        return esc_config_data.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(esc_config_data.uri);
    }

    public static final String prefix = "esc_config_data";
    public String prefix() {
        return esc_config_data.prefix;
    }

    public esc_config_data() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
