/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/esc_opdata_devstats.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module esc_opdata_devstats.yang */
public class esc_opdata_devstats extends ConfNamespace {
    public static final int hash = 583018869;
    public int hash() {
        return esc_opdata_devstats.hash;
    }

    public static final String id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_opdata_devstats";
    public String id() {
        return esc_opdata_devstats.id;
    }

    public static final String uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_opdata_devstats";
    public String uri() {
        return esc_opdata_devstats.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(esc_opdata_devstats.uri);
    }

    public static final String prefix = "esc_opdata_devstats";
    public String prefix() {
        return esc_opdata_devstats.prefix;
    }

    public esc_opdata_devstats() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
