/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/esc_port_forwarding.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module esc_port_forwarding.yang */
public class esc_port_forwarding extends ConfNamespace {
    public static final int hash = 1514235690;
    public int hash() {
        return esc_port_forwarding.hash;
    }

    public static final String id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_port_forwarding";
    public String id() {
        return esc_port_forwarding.id;
    }

    public static final String uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_port_forwarding";
    public String uri() {
        return esc_port_forwarding.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(esc_port_forwarding.uri);
    }

    public static final String prefix = "esc_port_forwarding";
    public String prefix() {
        return esc_port_forwarding.prefix;
    }

    public esc_port_forwarding() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
