/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/esc_file_server.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module esc_file_server.yang */
public class esc_file_server extends ConfNamespace {
    public static final int hash = 884311474;
    public int hash() {
        return esc_file_server.hash;
    }

    public static final String id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_file_server";
    public String id() {
        return esc_file_server.id;
    }

    public static final String uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_file_server";
    public String uri() {
        return esc_file_server.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(esc_file_server.uri);
    }

    public static final String prefix = "esc_file_server";
    public String prefix() {
        return esc_file_server.prefix;
    }

    public esc_file_server() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
