/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/esc_policies.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module esc_policies.yang */
public class esc_policies extends ConfNamespace {
    public static final int hash = 259963892;
    public int hash() {
        return esc_policies.hash;
    }

    public static final String id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_policies";
    public String id() {
        return esc_policies.id;
    }

    public static final String uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_policies";
    public String uri() {
        return esc_policies.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(esc_policies.uri);
    }

    public static final String prefix = "esc_policies";
    public String prefix() {
        return esc_policies.prefix;
    }

    public esc_policies() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
