/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/esc_container_services.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module esc_container_services.yang */
public class esc_container_services extends ConfNamespace {
    public static final int hash = 1700787781;
    public int hash() {
        return esc_container_services.hash;
    }

    public static final String id = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_containers";
    public String id() {
        return esc_container_services.id;
    }

    public static final String uri = "_esc-nc-1.0:esc-nc-1.0#http://www.cisco.com/esc/esc_containers";
    public String uri() {
        return esc_container_services.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(esc_container_services.uri);
    }

    public static final String prefix = "esc_containers";
    public String prefix() {
        return esc_container_services.prefix;
    }

    public esc_container_services() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
