/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/nso-licensing-proxy.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module nso-licensing-proxy.yang */
public class nsoLicensingProxy extends ConfNamespace {
    public static final int hash = 1452370634;
    public int hash() {
        return nsoLicensingProxy.hash;
    }

    public static final String id = "_esc-nc-1.0:esc-nc-1.0#http://cisco.com/yang/nso/licensing-proxy";
    public String id() {
        return nsoLicensingProxy.id;
    }

    public static final String uri = "_esc-nc-1.0:esc-nc-1.0#http://cisco.com/yang/nso/licensing-proxy";
    public String uri() {
        return nsoLicensingProxy.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(nsoLicensingProxy.uri);
    }

    public static final String prefix = "licensing-proxy";
    public String prefix() {
        return nsoLicensingProxy.prefix;
    }

    public nsoLicensingProxy() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _unique_id = 1542040645;
    public static final String _unique_id_ = "unique-id";
    public static final int    _n = 1951310448;
    public static final String _n_ = "n";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _nso_licensing_proxy = 2113528637;
    public static final String _nso_licensing_proxy_ = "nso-licensing-proxy";
    public static final int    _entitlement = 1163688895;
    public static final String _entitlement_ = "entitlement";
}
