/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-esc-nc-1.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-esc-nc-1.0.yang */
public class tailfNedIdEscNc1_0 extends ConfNamespace {
    public static final int hash = 1343644036;
    public int hash() {
        return tailfNedIdEscNc1_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/esc-nc-1.0";
    public String id() {
        return tailfNedIdEscNc1_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/esc-nc-1.0";
    public String uri() {
        return tailfNedIdEscNc1_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdEscNc1_0.uri);
    }

    public static final String prefix = "esc-nc-1.0";
    public String prefix() {
        return tailfNedIdEscNc1_0.prefix;
    }

    public tailfNedIdEscNc1_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _esc_nc_10x2e0 = 1189376274;
    public static final String _esc_nc_10x2e0_ = "esc-nc-1.0";
}
