/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-esc-nc.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.esc.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-esc-nc.yang */
public class tailfNedIdEscNc extends ConfNamespace {
    public static final int hash = 1092283822;
    public int hash() {
        return tailfNedIdEscNc.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/esc-nc";
    public String id() {
        return tailfNedIdEscNc.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/esc-nc";
    public String uri() {
        return tailfNedIdEscNc.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdEscNc.uri);
    }

    public static final String prefix = "esc-nc";
    public String prefix() {
        return tailfNedIdEscNc.prefix;
    }

    public tailfNedIdEscNc() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    ned_id = 1379098150;
    public static final String ned_id_ = "esc-nc:esc-nc";
    public static final int    _esc_nc = 1379098150;
    public static final String _esc_nc_ = "esc-nc";
}
